package com.decafe.resources.files;

public abstract class ImageFiles {

    public static final String EXTENSION_PNG = ".png";
    public final static String COFI_BREW_UP = "CofiBrewUp" + EXTENSION_PNG;
    public static final String COFI_BREW_CAKE_LEFT = "CofiBrewCakeLeft"  + EXTENSION_PNG;
    public static final String COFI_BREW_COFFEE_LEFT = "CofiBrewCoffeeLeft" + EXTENSION_PNG;
    public static final String SIMLEY_GREEN = "smileygreen" + EXTENSION_PNG;
    public static final String SMILEY_YELLOW = "smileyyellow" + EXTENSION_PNG;
    public static final String SMILEY_RED = "smileyred" + EXTENSION_PNG;
    public static final String BUBBLE_CAKE_TOP_LEFT = "bubbleCakeTopLeft" + EXTENSION_PNG;
    public static final String BUBBLE_CAKE_TOP_RIGHT = "bubbleCakeTopRight" + EXTENSION_PNG;
    public static final String BUBBLE_CAKE_BOTTOM_RIGHT = "bubbleCakeBottomRight" + EXTENSION_PNG;
    public static final String BUBBLE_COFFEE_TOP_LEFT = "bubbleCoffeeTopLeft" + EXTENSION_PNG;
    public static final String BUBBLE_COFFEE_TOP_RIGHT = "bubbleCoffeeTopRight" + EXTENSION_PNG;
    public static final String BUBBLE_COFFEE_BOTTOM_RIGHT = "bubbleCoffeeBottomRight" + EXTENSION_PNG;
    public static final String COIN = "coin" + EXTENSION_PNG;
    public static final String COFI_BREW_CAKE_UP = "CofiBrewCakeUp" + EXTENSION_PNG;
    public static final String COFI_BREW_COFFEE_UP = "CofiBrewCoffeeUp" + EXTENSION_PNG;
    public static final String COFI_BREW_DOWN = "CofiBrewDown" + EXTENSION_PNG;
    public static final String COFI_BREW_CAKE_DOWN = "CofiBrewCakeDown" + EXTENSION_PNG;
    public static final String COFI_BREW_COFFEE_DOWN = "CofiBrewCoffeeDown" + EXTENSION_PNG;
    public static final String COFI_BREW_LEFT = "CofiBrewLeft" + EXTENSION_PNG;
    public static final String COFI_BREW_RIGHT = "CofiBrewRight" + EXTENSION_PNG;
    public static final String COFI_BREW_CAKE_RIGHT = "CofiBrewCakeRight" + EXTENSION_PNG;
    public static final String COFI_BREW_COFFEE_RIGHT = "CofiBrewCoffeeRight" + EXTENSION_PNG;
    public static final String START_COFFEE_HOT = "startCoffeeHot" + EXTENSION_PNG;
    public static final String START_COFFEE = "startCoffee" + EXTENSION_PNG;
    public static final String QUITE_END_SCREEN_BRIGHTER = "quitEndScreenBrighter" + EXTENSION_PNG;
    public static final String QUIT_END_SCREEN = "quitEndScreen" + EXTENSION_PNG;
    public static final String INSTRUCTIONS_GOT_IT = "instructionsGotIt" + EXTENSION_PNG;
    public static final String INSTRUCTIONS_GOT_IT_BRIGHTER = "instructionsGotItBrighter" + EXTENSION_PNG;
    public static final String PLAY_AGAIN_BRIGHTER = "playAgainBrighter" + EXTENSION_PNG;
    public static final String PLAY_AGAIN = "playAgain" + EXTENSION_PNG;
    public static final String BACK_TO_START_MENU_BRIGHTER = "backToStartMenuBrighter" + EXTENSION_PNG;
    public static final String BACK_TO_START_MENU = "backToStartMenu" + EXTENSION_PNG;
    public static final String COFFEE_MACHINE_WITH_COFFEE = "coffeeMachineWithCoffee" + EXTENSION_PNG;
    public static final String COFFEE_MACHINE = "coffeeMachine" + EXTENSION_PNG;
    public static final String KITCHEN_AID_USED = "kitchenAidUsed" + EXTENSION_PNG;
    public static final String KITCHEN_AID = "kitchenAid" + EXTENSION_PNG;
    public static final String COFFEE_UPGRADE = "coffeeUpgrade" + EXTENSION_PNG;
    public static final String COFFEE_USED = "coffeeUsed" + EXTENSION_PNG;
    public static final String CAKE_UPGRADE = "cakeUpgrade" + EXTENSION_PNG;
    public static final String CAKE_USED = "cakeUsed" + EXTENSION_PNG;
    public static final String UPGRADE_SKATES = "upgradeSkates" + EXTENSION_PNG;
    public static final String UPGRADE_SKATES_USED = "upgradeSkatesUsed" + EXTENSION_PNG;
    public static final String FIVE_COINS = "5coins" + EXTENSION_PNG;
    public static final String FOUR_COINS = "4coins" + EXTENSION_PNG;
    public static final String THREE_COINS = "3coins" + EXTENSION_PNG;
}
